config/routes.rb
Rails.application.routes.draw do
  resources :paradas
  resources :caronas
  resources :unidades
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/carona.rb
class Carona < ApplicationRecord
  has_many :paradas, dependent: :destroy, inverse_of: :carona
  accepts_nested_attributes_for :paradas, allow_destroy: true, reject_if: :all_blank
  validates :nome, presence: true
  validates :partida, presence: true
  validates :dia, presence: true
  validates :destino, presence: true
  validates :hora, presence: true
  validates :passageiros, presence: true
  validates :valor, presence: true
  validates_format_of :valor, with: /\A\d+(.\d{1,2})?\z/, message: "Valor até duas casas decimais"
  validate :npassageiros
  
  private

  def npassageiros
    unless (1..4).include?(passageiros)
      errors.add(:passageiros, "dem ser de no mínimo 1 e no máximo 4")
    end
  end

end

app/models/parada.rb
class Parada < ApplicationRecord
  belongs_to :carona
end

app/models/unidade.rb
class Unidade < ApplicationRecord
  validates :nome, :endereco, :numero, :bairro, :cidade, :cep, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  def set_locale
    if params[:locale]
      cookies[:locale] = params[:locale]
    end
    if cookies[:locale]
      if I18n.locale != cookies[:locale]
        I18n.locale = cookies[:locale]
      end
    end
  end
end

app/controllers/caronas_controller.rb
class CaronasController < ApplicationController
  before_action :set_carona, only: %i[ show edit update destroy ]

  def index
    @caronas = Carona.all
    @paradas = Parada.all
    ordenado_por = params[:order] == 'asc' ? 'asc' : 'desc'
    @caronas = @caronas.order("dia #{ordenado_por}")
  end

  def show
  end

  def new
    @carona = Carona.new
    @unidades = Unidade.where(data_desativacao: '')
    @carona.hora = Time.current
    @carona.dia = Date.current
  end

  def edit
    @unidades = Unidade.where(data_desativacao: '')
  end

  def create
    @carona = Carona.new(carona_params)
    respond_to do |format|
      if @carona.save
        format.html { redirect_to carona_url(@carona), notice: "Carona criada com sucesso." }
        format.json { render :show, status: :created, location: @carona }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @carona.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @carona.update(carona_params)
        format.html { redirect_to carona_url(@carona), notice: "Carona atualizada com sucesso." }
        format.json { render :show, status: :ok, location: @carona }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @carona.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @carona.destroy

    respond_to do |format|
      format.html { redirect_to caronas_url, notice: "Carona foi apagada com sucesso." }
      format.json { head :no_content }
    end
  end

  private
   
    def set_carona
      @carona = Carona.find(params[:id])
    end
  
    def carona_params
      params.require(:carona).permit(:nome, :partida ,:destino, :dia, :hora, :passageiros, :valor, :observacao, paradas_attributes: [:id, :endereco, :_destroy])
    end
end

app/controllers/paradas_controller.rb
class ParadasController < ApplicationController
  before_action :set_parada, only: %i[ show edit update destroy ]

  # GET /paradas or /paradas.json
  def index
    @paradas = Parada.all
  end

  # GET /paradas/1 or /paradas/1.json
  def show
  end

  # GET /paradas/new
  def new
    @parada = Parada.new
  end

  # GET /paradas/1/edit
  def edit
  end

  # POST /paradas or /paradas.json
  def create
    @parada = Parada.new(parada_params)

    respond_to do |format|
      if @parada.save
        format.html { redirect_to parada_url(@parada), notice: "Parada was successfully created." }
        format.json { render :show, status: :created, location: @parada }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @parada.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paradas/1 or /paradas/1.json
  def update
    respond_to do |format|
      if @parada.update(parada_params)
        format.html { redirect_to parada_url(@parada), notice: "Parada was successfully updated." }
        format.json { render :show, status: :ok, location: @parada }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @parada.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paradas/1 or /paradas/1.json
  def destroy
    @parada.destroy

    respond_to do |format|
      format.html { redirect_to paradas_url, notice: "Parada was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parada
      @parada = Parada.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def parada_params
      params.require(:parada).permit(:endereco, :carona_id)
    end
end

app/controllers/unidades_controller.rb
class UnidadesController < ApplicationController
  before_action :set_unidade, only: %i[ show edit update destroy ]
 
  # GET /unidades or /unidades.json
  def index
    @unidades = Unidade.all
  end

  # GET /unidades/1 or /unidades/1.json
  def show
  end

  # GET /unidades/new
  def new
    @unidade = Unidade.new
  end

  # GET /unidades/1/edit
  def edit
  end

  # POST /unidades or /unidades.json
  def create
    @unidade = Unidade.new(unidade_params)

    respond_to do |format|
      if @unidade.save
        format.html { redirect_to unidade_url(@unidade), notice: "Unidade criada com sucesso." }
        format.json { render :show, status: :created, location: @unidade }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @unidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unidades/1 or /unidades/1.json
  def update
    respond_to do |format|
      if @unidade.update(unidade_params)
        format.html { redirect_to unidade_url(@unidade), notice: "Campus Atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @unidade }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @unidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unidades/1 or /unidades/1.json
  def destroy
    @unidade.destroy

    respond_to do |format|
      format.html { redirect_to unidades_url, notice: "Unidade apagada com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unidade
      @unidade = Unidade.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def unidade_params
      params.require(:unidade).permit(:nome, :endereco, :numero, :bairro, :cidade, :cep, :data_desativacao)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/caronas_helper.rb
module CaronasHelper
  def horaf(data)
    data.strftime("%H:%M")
  end

  def diaf(dia)
    dia.strftime("%d/%m/%Y")
  end

end

app/helpers/paradas_helper.rb
module ParadasHelper
end

app/helpers/unidades_helper.rb
module UnidadesHelper
  def data_formatada(data) 
    Date.parse(data).strftime("%d/%m/%Y") if data.present?
  end
  
	def cep_formatado(cep)
	  cep.split('').insert(5, '-').join
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/caronas/_form.html.erb
<%= simple_form_for(@carona, html: { class: 'form' }) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs row">
    <div class="col-md-6">
      <%= f.input :nome, input_html: { class: 'form-control', style: 'background-color: #f5f5f5;' }, placeholder: "#{Carona.human_attribute_name(:nome)}", label: false %>
    </div>

    <div class="col-md-6">
      <select id="unidade_tipo" class="form-control" style="background-color: #f5f5f5;">
        <option value="" disabled selected><%= t('select.op')%></option>
        <option value="partida">partida</option>
        <option value="destino"><%= t('select.end')%></option>
      </select>
    </div>

  <div class="col-md-6">
    <%= f.input :partida, collection: @unidades, label_method: :nome, value_method: :nome, include_blank: t('select.initial'), input_html: { class: 'form-control', style: 'background-color: #f5f5f5;', id: 'partida_select', hidden: true }, label: false %>
    <%= f.input :partida, input_html: { class: 'form-control', style: 'background-color: #f5f5f5;', id: 'partida_input', disabled: true, hidden: true, placeholder: Carona.human_attribute_name(:partida) }, label: false %>
  </div>

  <div class="col-md-6">
    <%= f.input :destino, input_html: { class: 'form-control', style: 'background-color: #f5f5f5;', id: 'destino_input', disabled: true, hidden: true, placeholder: Carona.human_attribute_name(:destino) }, label: false %>
    <%= f.input :destino, collection: @unidades, label_method: :nome, value_method: :nome, input_html: { class: 'form-control', style: 'background-color: #f5f5f5;', id: 'destino_select', hidden: true }, include_blank: t('select.end'), label: false %>
  </div>

    <div class="col-12">
      <div id="paradas">
        <%= f.simple_fields_for :paradas do |parada| %>
          <%= render 'parada_fields', f: parada %>
        <% end %>
        <div class="links">
          <%= link_to_add_association t('links.stoppoint'), f, :paradas, class: 'btn btn-sm btn-dark', style: 'margin: 1% 0;' %>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <%= f.date_field :dia, as: :string, class: 'form-control', style: 'background-color: #f5f5f5;', placeholder: "#{Carona.human_attribute_name(:dia)}", label: false %>
    </div> 

    <div class="col-md-6">
      <%= f.input :hora, input_html: { class: 'form-control', style: 'background-color: #f5f5f5;', id: '#carona_hora'}, placeholder: "#{Carona.human_attribute_name(:hora)}", label: false %>
    </div>

    <div class="col-md-6" style='margin-top: 1%'>
      <%= f.input :passageiros, input_html: { class: 'form-control', style: 'background-color: #f5f5f5;' }, placeholder: "#{Carona.human_attribute_name(:passageiros)}", label: false %>
    </div>

    <div class="col-md-6" style='margin-top: 1%'>
      <%= f.input :valor, placeholder: "#{Carona.human_attribute_name(:valor)}", label: false, input_html: { class: 'form-control', style: 'background-color: #f5f5f5;' }%>
    </div>

    <div class="col-md-6">
      <%= f.input :observacao, input_html: { class: 'form-control', style: 'background-color: #f5f5f5; resize: none;' }, placeholder: "#{Carona.human_attribute_name(:observacao)}", label: false %>
    </div>
  </div> 

  <div class="form-actions">
    <%= f.button :submit, t('links.save'),class: 'btn btn-dark'%>
  </div>
<% end %>

app/views/caronas/_parada_fields.html.erb
<div class="nested-fields">
    <%= f.input :endereco %>
    <%= link_to_remove_association t('links.rmstoppoint'), f, class: 'btn btn-sm btn-danger', style: 'margin: 1% 0;' %>
</div>

app/views/caronas/edit.html.erb
<h1>Editing Carona</h1>

<%= render 'form', carona: @carona %>

<%= link_to t('links.show'), @carona, class: 'btn btn-sm btn-dark', style: 'margin-top: 1%' %> 
<%= link_to t('links.back'), caronas_path, class: 'btn btn-sm btn-dark', style: 'margin-top: 1%'%>

app/views/caronas/index.html.erb
<p id="notice"><%= notice %></p>

<div class="d-flex justify-content-between align-items-center">
  <h1><%= t('activerecord.models.carona.other') %></h1>
  <div>
    <div class="dropdown">
      <a class="dropdown-toggle" href="#" id="Dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" style='text-decoration: none;color: #000'>
        <%= t('links.order') %>
      </a>
      <div class="dropdown-menu" aria-labelledby="Dropdown">
        <div>
          <%= link_to "Data Ascendente", caronas_path(order: 'asc'), class: "dropdown-item" %>
        </div>
        <div>
          <%= link_to "Data Descendente", caronas_path(order: 'desc'), class: "dropdown-item" %>
        </div>
      </div>
    </div>
  </div>
</div>

<table class="table table-bordered table-striped table-dark">
   <thead>
    <tr>
      <th><%= @caronas.human_attribute_name(:nome)%></th>
      <th><%= @caronas.human_attribute_name(:partida)%></th>
      <th><%= @caronas.human_attribute_name(:destino)%></th>
      <th><%= @caronas.human_attribute_name(:dia)%></th>
      <th><%= @caronas.human_attribute_name(:hora)%></th>
      <th><%= @caronas.human_attribute_name(:passageiros)%></th>
      <th><%= @caronas.human_attribute_name(:valor)%></th>
      <th><%= @caronas.human_attribute_name(:observacao)%></th>
      <th><%= t('table.stops')%></th>
      <th colspan="3" ><%= t('table.options')%></th>
    </tr>
  </thead>

  <tbody>
    <% @caronas.each do |carona| %>
      <tr>
        <td><%= carona.nome %></td>
        <td><%= carona.partida %></td>
        <td><%= carona.destino %></td>
        <td><%= diaf(carona.dia) %></td>
        <td><%= horaf(carona.hora) %></td>
        <td><%= carona.passageiros %></td>
        <td>R$<%= carona.valor %></td>
        <td><%= carona.observacao %></td>
        <td>
          <% if carona.paradas.present? %>
            Sim
          <% else %>
             Não
           <% end %>
        </td>
        <td><%= link_to t('links.show'), carona %></td>
        <td><%= link_to t('links.edit'), edit_carona_path(carona)%></td>
        <td><%= link_to 'Delete', carona, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('links.newride'), new_carona_path, class: 'btn btn-dark' %>

app/views/caronas/new.html.erb
<h1>Nova Carona</h1>

<%= render 'form', carona: @carona %>

<%= link_to 'Voltar', caronas_path, class: 'btn btn-secondary', style: 'margin-top: 1%' %>

app/views/caronas/show.html.erb
<h2 id="notice"><%= notice %></h2>

<div class="d-flex" style="margin-left: 30%">
  <h1>Corrida</h1>
</div>

<div class="d-flex" style="justify-content: center">
  <table class="table table-striped table-dark" style="width: 40%">
    <tbody>
      <tr>
        <th><%= Carona.human_attribute_name(:nome)%></th>
        <td><%= @carona.nome %></td>
      </tr>
      <tr>
        <th><%= Carona.human_attribute_name(:partida)%></th>
        <td><%= @carona.partida %></td>
      </tr>
      <tr>
        <th><%= Carona.human_attribute_name(:destino)%></th>
        <td><%= @carona.destino %></td>
      </tr>
      <tr>
        <th><%= Carona.human_attribute_name(:dia)%></th>
        <td><%= diaf(@carona.dia) %></td>
      </tr>
      <tr>
        <th><%= Carona.human_attribute_name(:hora)%></th>
        <td><%= horaf(@carona.hora) %></td>
      </tr>
      <tr>
        <th><%= Carona.human_attribute_name(:passageiros)%></th>
        <td><%= @carona.passageiros %></td>
      </tr>
      <tr>
        <th><%= Carona.human_attribute_name(:valor)%></th>
        <td><%= @carona.valor %></td>
      </tr>
      <tr>
        <th><%= Carona.human_attribute_name(:observacao)%></th>
        <td><%= @carona.observacao %></td>
      </tr>
    </tbody>
  </table>
</div>
<div class="d-flex" style="margin-left: 30%">
  <%= link_to t('links.edit'), edit_carona_path(@carona), class: 'btn btn-sm btn-dark' %>
  <%= link_to t('links.back'), caronas_path, class: 'btn btn-sm btn-dark', style: 'margin-left: 1%' %>
</div>
<% if @carona.paradas.presence %>
  <div class="d-flex" style="margin-left: 30%">
    <h1><%= t('activerecord.models.parada.other') %></h1>
  </div>
  <% @carona.paradas.each_with_index do |parada, i| %>
    <div class="d-flex" style="justify-content: center">
      <table class="table table-striped table-dark" style="width: 40%">
        <tbody>
          <tr>
            <th><%= "#{t('activerecord.models.parada.one')} - #{i+1}" %></th>
            <td><%= parada.endereco %></td>
          </tr>
        </tbody>
      </table>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Teste</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'unidade_escolha', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render './partials/navbar'%>
    <%= yield :welcome %>
    <div class="container corpo">
      <%= yield %>
    </div>
  </body>
</html>

app/views/paradas/_form.html.erb
<%= simple_form_for(@parada) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :endereco %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/paradas/edit.html.erb
<h1>Editing Parada</h1>

<%= render 'form', parada: @parada %>

<%= link_to 'Show', @parada %> |
<%= link_to 'Back', paradas_path %>

app/views/paradas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Paradas</h1>

<table>
  <thead>
    <tr>
      <th>Endereco</th>
      <th>Carona</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paradas.each do |parada| %>
      <tr>
        <td><%= parada.endereco %></td>
        <td><%= parada.carona_id %></td>
        <td><%= link_to t('links.show'), parada %></td>
        <td><%= link_to t('links.edit'), edit_parada_path(parada) %></td>
        <td><%= link_to t('links.delete'), parada, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('links.newstop'), new_parada_path %>

app/views/paradas/new.html.erb
<h1>New Parada</h1>

<%= render 'form', parada: @parada %>

<%= link_to 'Back', paradas_path %>

app/views/paradas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Endereco:</strong>
  <%= @parada.endereco %>
</p>

<p>
  <strong>Carona:</strong>
  <%= @parada.carona_id %>
</p>

<%= link_to 'Edit', edit_parada_path(@parada) %> |
<%= link_to 'Back', paradas_path %>

app/views/partials/_header_welcome.erb
<header class="bg-primary bg-gradient text-white">
  <div class="container px-4 text-center">
    <h1 class="fw-bolder"><%= t('welcome.title') %></h1>
    <p class="lead"><%= t('welcome.subtitle') %></p>
    <a class="btn btn-lg btn-light" href="#about"><%= t('welcome.button') %></a>
  </div>
</header>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
  <div class="container px-4">
    <%= link_to 'Universidade Federal Fluminense', root_path, class: 'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item"><%= link_to 'Campus', unidades_path, class: 'nav-link'%></li>
        <li class="nav-item"><%= link_to "Caronas", caronas_path, class: 'nav-link' %></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Idioma
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
              <div class="image-link-container">
                <img src="https://www.curitiba.pr.leg.br/atividade-parlamentar/legislacao/imagens/bandeira-do-brasil.png" width="25" height="20">
                <%= link_to "Português", "#{request.path}?locale=pt-BR", class: 'dropdown-item' %>
              </div>
            </li>
            <li>
              <div class= "image-link-container">
                <img src="https://www.gov.br/agricultura/pt-br/assuntos/relacoes-internacionais/agro-mais-investimentos/imagens/bandeira-dos-estados-unidos.png/@@images/image.png" width="25" height="20">
                <%= link_to "English", "#{request.path}?locale=en", class: 'dropdown-item' %>
              </div>
            </li>
          </ul>
        </li>
    </div>
  </div>
</nav>

app/views/unidades/_tabela_campus.html.erb
<table class="table table-bordered table-striped table-dark ativo">
    <thead>
      <tr>
        <th><%=@unidades.human_attribute_name(:nome)%></th>
        <th><%=@unidades.human_attribute_name(:endereco)%></th>
        <th><%=@unidades.human_attribute_name(:numero)%></th>
        <th><%=@unidades.human_attribute_name(:bairro)%></th>
        <th><%=@unidades.human_attribute_name(:cidade)%></th>
        <th><%=@unidades.human_attribute_name(:cep)%></th>
        <th><%=@unidades.human_attribute_name(:data_desativacao)%></th>
        <th colspan="3"><%=t('table.options')%></th>
      </tr>
    </thead>

    <tbody>
      <h3><%= t('available') %></h3>
      <% @unidades.each do |unidade| %>
        <% if unidade.data_desativacao == ''%>
          <tr>
            <td><%= unidade.nome %></td>
            <td><%= unidade.endereco %></td>
            <td><%= unidade.numero %></td>
            <td><%= unidade.bairro %></td>
            <td><%= unidade.cidade %></td>
            <td><%= cep_formatado(unidade.cep) %></td>
            <td><%= unidade.data_desativacao %></td>
            <td><%= link_to t('links.show'), unidade %></td>
            <td><%= link_to t('links.edit'), edit_unidade_path(unidade) %></td>
            <td><%= link_to 'Delete', unidade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
</table>

<table class="table table-bordered table-striped table-dark">
  <thead>
    <tr>
      <th><%=@unidades.human_attribute_name(:nome)%></th>
      <th><%=@unidades.human_attribute_name(:endereco)%></th>
      <th><%=@unidades.human_attribute_name(:numero)%></th>
      <th><%=@unidades.human_attribute_name(:bairro)%></th>
      <th><%=@unidades.human_attribute_name(:cidade)%></th>
      <th><%=@unidades.human_attribute_name(:cep)%></th>
      <th><%=@unidades.human_attribute_name(:data_desativacao)%></th>
      <th colspan="3"><%=t('table.options')%></th>
    </tr>
  </thead>

  <tbody>
    <h3><%= t('unavailable') %></h3>
    <% @unidades.each do |unidade| %>
      <% if unidade.data_desativacao != ''%>
        <tr>
          <td><%= unidade.nome %></td>
          <td><%= unidade.endereco %></td>
          <td><%= unidade.numero %></td>
          <td><%= unidade.bairro %></td>
          <td><%= unidade.cidade %></td>
          <td><%= cep_formatado(unidade.cep) %></td>
          <td><%= unidade.data_desativacao %></td>
          <td><%= link_to t('links.show'), unidade %></td>
          <td><%= link_to t('links.edit'), edit_unidade_path(unidade) %></td>
          <td><%= link_to t('links.delete'), unidade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/unidades/edit.html.erb
<h1>Editar Unidade</h1>

<%= render 'form', unidade: @unidade %>

<%= link_to t('links.show'), @unidade, class: 'btn btn-dark', style: "margin-top: 1%"%> 
<%= link_to t('links.back'), unidades_path, class: 'btn btn-dark', style: "margin-top: 1%"%>

app/views/unidades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Unidades</h1>

<%= render 'tabela_campus'%>

<br>

<%= link_to t('links.newunit'), new_unidade_path, class: 'btn btn-dark' %>

app/views/unidades/new.html.erb
<h1>Nova Unidade</h1>

<%= render 'form', unidade: @unidade %>
</br>
<%= link_to 'Voltar', unidades_path, class: 'btn btn-secondary' %>

app/views/unidades/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Unidade</h1>
<div class="d-flex" style="justify-content: center">
  <table class="table table-striped table-dark" style="width: 40% ">
    <tbody>
      <tr>
        <th><%= Unidade.human_attribute_name(:nome) %></th>
        <td><%= @unidade.nome %></td>
      </tr>
      <tr>
        <th><%= Unidade.human_attribute_name(:endereco) %></th>
        <td><%= @unidade.endereco %></td>
      </tr>
      <tr>
        <th><%= Unidade.human_attribute_name(:numero) %></th>
        <td><%= @unidade.numero%></td>
      </tr>
      <tr>
        <th><%= Unidade.human_attribute_name(:bairro) %></th>
        <td><%= @unidade.bairro %></td>
      </tr>
      <tr>
        <th><%= Unidade.human_attribute_name(:cidade) %></th>
        <td><%= @unidade.cidade %></td>
      </tr>
      <tr>
        <th><%= Unidade.human_attribute_name(:cep) %></th>
        <td><%= @unidade.cep %></td>
      </tr>
      <tr>
        <th><%= Unidade.human_attribute_name(:data_desativacao) %></th>
        <td><%= @unidade.data_desativacao %></td>
      </tr>
    </tbody>
  </table>
</div>
<div class="d-flex-direction: column" style="margin-left: 30%">
  <%= link_to t('links.edit'), edit_unidade_path(@unidade), class: 'btn btn-dark ' %>
  <%= link_to t('links.back'), unidades_path, class: 'btn btn-dark' %>
</div>  

app/views/welcome/index.html.erb
<% content_for :welcome do %>
  <%= render './partials/header_welcome' %>
<% end %>